config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    restricted_subdomains = %w{ www admin }
    request.subdomain.present? && !restricted_subdomains.include?(request.subdomain)
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end


Rails.application.routes.draw do

  resources :memberinvites
  resources :memberships
  devise_for :users, :controllers => {:registrations => "registrations"}

  constraints(SubdomainPresent) do
    root 'pages#account_home', as: :subdomain_root
    get 'welcome', to: 'pages#welcome', as: :welcome

    resources :projects do
      resources :posts
    end

  end

  constraints(SubdomainBlank) do
    root 'pages#home'
    get 'pages/about'
    resources :accounts
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates_presence_of :name
  belongs_to :project
  default_scope { where(project_id: Project.current_id) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to project_posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to project_posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to project_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :description, :project_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for([@current_project, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <input type="hidden" name="post[project_id]" id="project_id" value="<%= @current_project.id %>" />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', project_post_path(@current_project, @post) %> |
<%= link_to 'Back', project_posts_path(@current_project) %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<p>Current project is: <%= "#{@current_project.name}" %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
      <td><%= post.name %></td>
      <td><%= post.description %></td>
      <td><%= link_to 'Show', project_post_path(@current_project, post) %></td>
      <td><%= link_to 'Edit', edit_project_post_path(@current_project, post) %></td>
      <td><%= link_to 'Destroy', project_post_path(@current_project, post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_project_post_path(@current_project) %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', project_posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Current Project is: <%= @current_project.name %></h2>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>

  <p><%= link_to 'Edit', edit_project_post_path(@current_project, @post) %></p>
  <p><%= link_to 'Back', project_posts_path %></p>
  <p><%= link_to 'Destroy', project_post_path(@current_project, @post), method: :delete, data: { confirm: 'Are you sure?' } %></p>
</p>